/* Generated by           cobc 3.2.0 */
/* Generated from         eod.cob */
/* Generated at           Feb 03 2026 21:12:31 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -g eod.cob */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Picture strings */

static const cob_pic_symbol p_1[] = {
	{'Z', 3},
	{',', 1},
	{'Z', 3},
	{',', 1},
	{'Z', 2},
	{'9', 1},
	{'.', 1},
	{'9', 2},
	{'\0', 1}
};


/* Attributes */

static const cob_field_attr a_1 =	{0x10,   7,   0, 0x0000, NULL};
static const cob_field_attr a_2 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_3 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_4 =	{0x10,   9,   2, 0x0000, NULL};
static const cob_field_attr a_5 =	{0x10,  11,   2, 0x0000, NULL};
static const cob_field_attr a_6 =	{0x24,  11,   2, 0x0000, p_1};
static const cob_field_attr a_7 =	{0x01,   0,   0, 0x0000, NULL};
static const cob_field_attr a_8 =	{0x10,   1,   0, 0x1000, NULL};

static const cob_field_attr cob_all_attr = {0x22, 0, 0, 0, NULL};


/* Constants */
static const cob_field c_1	= {14, (cob_u8_ptr)"ACCOUNT FROZEN", &a_2};
static const cob_field c_2	= {24, (cob_u8_ptr)"INVALID TRANSACTION TYPE", &a_2};
static const cob_field c_3	= {23, (cob_u8_ptr)"ZERO AMOUNT NOT ALLOWED", &a_2};
static const cob_field c_4	= {18, (cob_u8_ptr)"INSUFFICIENT FUNDS", &a_2};
static const cob_field c_5	= {5, (cob_u8_ptr)"ACCT=", &a_2};
static const cob_field c_6	= {6, (cob_u8_ptr)" TYPE=", &a_2};
static const cob_field c_7	= {5, (cob_u8_ptr)" AMT=", &a_2};
static const cob_field c_8	= {8, (cob_u8_ptr)" REASON=", &a_2};
static const cob_field c_9	= {27, (cob_u8_ptr)"ACCOUNT NOT FOUND IN MASTER", &a_2};
static const cob_field c_10	= {35, (cob_u8_ptr)"======== END OF DAY REPORT ========", &a_2};
static const cob_field c_11	= {25, (cob_u8_ptr)"TOTAL TRANSACTIONS READ: ", &a_2};
static const cob_field c_12	= {25, (cob_u8_ptr)"TOTAL SUCCESSFUL:        ", &a_2};
static const cob_field c_13	= {25, (cob_u8_ptr)"TOTAL FAILED:            ", &a_2};
static const cob_field c_14	= {25, (cob_u8_ptr)"TOTAL DEPOSIT AMOUNT:    ", &a_2};
static const cob_field c_15	= {25, (cob_u8_ptr)"TOTAL WITHDRAW AMOUNT:   ", &a_2};
static const cob_field c_16	= {35, (cob_u8_ptr)"===================================", &a_2};
static const cob_field c_17	= {1, (cob_u8_ptr)"0", &a_8};
static const cob_field c_18	= {15, (cob_u8_ptr)"acct-master.dat", &a_2};
static const cob_field c_19	= {9, (cob_u8_ptr)"trans.dat", &a_2};
static const cob_field c_20	= {28, (cob_u8_ptr)"./output/acct-master-new.dat", &a_2};
static const cob_field c_21	= {19, (cob_u8_ptr)"./output/report.txt", &a_2};
static const cob_field c_22	= {18, (cob_u8_ptr)"./output/error.log", &a_2};

static cob_field cob_all_zero	= {1, (cob_u8_ptr)"0", &cob_all_attr};


#define cob_nop	if (!module) cob_nop

