/* Generated by           cobc 3.2.0 */
/* Generated from         eod.cob */
/* Generated at           Feb 03 2026 21:12:31 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -g eod.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"eod.cob"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Feb 03 2026 21:12:31"
#define  COB_MODULE_DATE		20260203
#define  COB_MODULE_TIME		211231

/* Global variables */
#include "eod.c.h"

/* Function prototypes */

static int		EOD ();
static int		EOD_ (const int);
static void		EOD_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (EOD ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'EOD' */

/* ENTRY 'EOD' */

static int
EOD ()
{
  return EOD_ (0);
}

static int
EOD_ (const int entry)
{
  /* Program local variables */
  #include "eod.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 91        : Entry     EOD                     : eod.cob */
  l_2:;
#line 91 "eod.cob"
  ENTRY_EOD:	cob_nop ();
#line 105 "eod.c"

  /* Line: 91        : Paragraph MAIN                    : eod.cob */
#line 91 "eod.cob"
  PARAGRAPH_MAIN_l_4:	cob_nop ();
#line 110 "eod.c"

  /* Line: 92        : PERFORM            : eod.cob */
#line 92 "eod.cob"
  cob_nop ();
#line 115 "eod.c"
  /* PERFORM INIT-FILES */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 5;
  frame_ptr->return_address_ptr = &&l_16;
  goto l_5;
  l_16:
  frame_ptr--;

  /* Line: 93        : PERFORM            : eod.cob */
#line 93 "eod.cob"
  cob_nop ();
#line 129 "eod.c"
  /* PERFORM READ-MASTER */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 6;
  frame_ptr->return_address_ptr = &&l_17;
  goto l_6;
  l_17:
  frame_ptr--;

  /* Line: 94        : PERFORM            : eod.cob */
#line 94 "eod.cob"
  cob_nop ();
#line 143 "eod.c"
  /* PERFORM READ-TRANS */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 7;
  frame_ptr->return_address_ptr = &&l_18;
  goto l_7;
  l_18:
  frame_ptr--;

  /* Line: 96        : PERFORM            : eod.cob */
#line 96 "eod.cob"
  cob_nop ();
#line 157 "eod.c"
  for (;;)
  {
    /* Line: 96        : UNTIL              : eod.cob */
#line 96 "eod.cob"
    cob_nop ();
#line 163 "eod.c"
    if (((int)(int)(*(b_38) - (unsigned char)'Y') == 0))
      break;

    /* Line: 97        : IF                 : eod.cob */
#line 97 "eod.cob"
    cob_nop ();
#line 170 "eod.c"
    if ((!((int)(int)(*(b_40) - (unsigned char)'Y') == 0) && 
        ((int)memcmp (b_22, b_27, 5) == 0)))
    {

      /* Line: 98        : PERFORM            : eod.cob */
#line 98 "eod.cob"
      cob_nop ();
#line 178 "eod.c"
      /* PERFORM APPLY-ALL-TRANS-FOR-ACCOUNT */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 8;
      frame_ptr->return_address_ptr = &&l_19;
      goto l_8;
      l_19:
      frame_ptr--;
    }

    /* Line: 101       : PERFORM            : eod.cob */
#line 101 "eod.cob"
    cob_nop ();
#line 193 "eod.c"
    /* PERFORM WRITE-UPDATED-MASTER */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 12;
    frame_ptr->return_address_ptr = &&l_20;
    goto l_12;
    l_20:
    frame_ptr--;

    /* Line: 102       : PERFORM            : eod.cob */
#line 102 "eod.cob"
    cob_nop ();
#line 207 "eod.c"
    /* PERFORM READ-MASTER */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 6;
    frame_ptr->return_address_ptr = &&l_21;
    goto l_6;
    l_21:
    frame_ptr--;
  }

  /* Line: 105       : PERFORM            : eod.cob */
#line 105 "eod.cob"
  cob_nop ();
#line 222 "eod.c"
  /* PERFORM WRITE-TRAILING-TRANS-ERRORS */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 13;
  frame_ptr->return_address_ptr = &&l_22;
  goto l_13;
  l_22:
  frame_ptr--;

  /* Line: 106       : PERFORM            : eod.cob */
#line 106 "eod.cob"
  cob_nop ();
#line 236 "eod.c"
  /* PERFORM WRITE-REPORT */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 14;
  frame_ptr->return_address_ptr = &&l_23;
  goto l_14;
  l_23:
  frame_ptr--;

  /* Line: 107       : PERFORM            : eod.cob */
#line 107 "eod.cob"
  cob_nop ();
#line 250 "eod.c"
  /* PERFORM CLOSE-FILES */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 15;
  frame_ptr->return_address_ptr = &&l_24;
  goto l_15;
  l_24:
  frame_ptr--;

  /* Line: 108       : STOP RUN           : eod.cob */
#line 108 "eod.cob"
  cob_nop ();
#line 264 "eod.c"
  cob_stop_run (b_2);

  /* Line: 110       : Paragraph INIT-FILES              : eod.cob */
  l_5:;
#line 110 "eod.cob"
  PARAGRAPH_INIT__FILES_l_5:	cob_nop ();
#line 271 "eod.c"

  /* Line: 111       : OPEN               : eod.cob */
#line 111 "eod.cob"
  cob_nop ();
#line 276 "eod.c"
  cob_open (h_ACCT_MASTER, COB_OPEN_INPUT, 0, NULL);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_25;
    goto l_1;
    l_25:
    frame_ptr--;
  }

  /* Line: 112       : OPEN               : eod.cob */
#line 112 "eod.cob"
  cob_nop ();
#line 294 "eod.c"
  cob_open (h_TRANS_FILE, COB_OPEN_INPUT, 0, NULL);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_26;
    goto l_1;
    l_26:
    frame_ptr--;
  }

  /* Line: 113       : OPEN               : eod.cob */
#line 113 "eod.cob"
  cob_nop ();
#line 312 "eod.c"
  cob_open (h_ACCT_NEW, COB_OPEN_OUTPUT, 0, NULL);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_27;
    goto l_1;
    l_27:
    frame_ptr--;
  }

  /* Line: 114       : OPEN               : eod.cob */
#line 114 "eod.cob"
  cob_nop ();
#line 330 "eod.c"
  cob_open (h_REPORT_FILE, COB_OPEN_OUTPUT, 0, NULL);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_28;
    goto l_1;
    l_28:
    frame_ptr--;
  }

  /* Line: 115       : OPEN               : eod.cob */
#line 115 "eod.cob"
  cob_nop ();
#line 348 "eod.c"
  cob_open (h_ERROR_FILE, COB_OPEN_OUTPUT, 0, NULL);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_29;
    goto l_1;
    l_29:
    frame_ptr--;
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 5)
    goto *frame_ptr->return_address_ptr;

  /* Line: 117       : Paragraph READ-MASTER             : eod.cob */
  l_6:;
#line 117 "eod.cob"
  PARAGRAPH_READ__MASTER_l_6:	cob_nop ();
#line 371 "eod.c"

  /* Line: 118       : READ               : eod.cob */
#line 118 "eod.cob"
  cob_nop ();
#line 376 "eod.c"
  cob_read_next (h_ACCT_MASTER, NULL, 1);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    if (cob_glob_ptr->cob_exception_code == 0x0501)
    {

      /* Line: 120       : MOVE               : eod.cob */
#line 120 "eod.cob"
      cob_nop ();
#line 386 "eod.c"
      *(b_38) = 89;
    }
    else
    {
      /* USE PROCEDURE Default Error Handler */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_30;
      goto l_1;
      l_30:
      frame_ptr--;
    }
  }
  else
  {

    /* Line: 122       : CONTINUE           : eod.cob */
#line 122 "eod.cob"
    cob_nop ();
#line 408 "eod.c"
    ;
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 6)
    goto *frame_ptr->return_address_ptr;

  /* Line: 125       : Paragraph READ-TRANS              : eod.cob */
  l_7:;
#line 125 "eod.cob"
  PARAGRAPH_READ__TRANS_l_7:	cob_nop ();
#line 420 "eod.c"

  /* Line: 126       : READ               : eod.cob */
#line 126 "eod.cob"
  cob_nop ();
#line 425 "eod.c"
  cob_read_next (h_TRANS_FILE, NULL, 1);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    if (cob_glob_ptr->cob_exception_code == 0x0501)
    {

      /* Line: 128       : MOVE               : eod.cob */
#line 128 "eod.cob"
      cob_nop ();
#line 435 "eod.c"
      *(b_40) = 89;
    }
    else
    {
      /* USE PROCEDURE Default Error Handler */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_31;
      goto l_1;
      l_31:
      frame_ptr--;
    }
  }
  else
  {

    /* Line: 130       : ADD                : eod.cob */
#line 130 "eod.cob"
    cob_nop ();
#line 457 "eod.c"
    cob_add_int (&f_43, 1, 0);
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address_ptr;

  /* Line: 133       : Paragraph APPLY-ALL-TRANS-FOR-ACCOUNT: eod.cob */
  l_8:;
#line 133 "eod.cob"
  PARAGRAPH_APPLY__ALL__TRANS__FOR__ACCOUNT_l_8:	cob_nop ();
#line 469 "eod.c"

  /* Line: 134       : PERFORM            : eod.cob */
#line 134 "eod.cob"
  cob_nop ();
#line 474 "eod.c"
  for (;;)
  {
    /* Line: 134       : UNTIL              : eod.cob */
#line 134 "eod.cob"
    cob_nop ();
#line 480 "eod.c"
    if ((((int)(int)(*(b_40) - (unsigned char)'Y') == 0) || 
        ((int)memcmp (b_27, b_22, 5) != 0)))
      break;

    /* Line: 135       : PERFORM            : eod.cob */
#line 135 "eod.cob"
    cob_nop ();
#line 488 "eod.c"
    /* PERFORM VALIDATE-AND-APPLY-ONE-TRANS */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 9;
    frame_ptr->return_address_ptr = &&l_32;
    goto l_9;
    l_32:
    frame_ptr--;

    /* Line: 136       : PERFORM            : eod.cob */
#line 136 "eod.cob"
    cob_nop ();
#line 502 "eod.c"
    /* PERFORM READ-TRANS */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 7;
    frame_ptr->return_address_ptr = &&l_33;
    goto l_7;
    l_33:
    frame_ptr--;
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 8)
    goto *frame_ptr->return_address_ptr;

  /* Line: 139       : Paragraph VALIDATE-AND-APPLY-ONE-TRANS: eod.cob */
  l_9:;
#line 139 "eod.cob"
  PARAGRAPH_VALIDATE__AND__APPLY__ONE__TRANS_l_9:	cob_nop ();
#line 522 "eod.c"

  /* Line: 140       : IF                 : eod.cob */
#line 140 "eod.cob"
  cob_nop ();
#line 527 "eod.c"
  if (((int)(int)(*(b_22 + 24) - (unsigned char)'F') == 0))
  {

    /* Line: 141       : MOVE               : eod.cob */
#line 141 "eod.cob"
    cob_nop ();
#line 534 "eod.c"
    cob_move ((cob_field *)&c_1, &f_48);

    /* Line: 142       : PERFORM            : eod.cob */
#line 142 "eod.cob"
    cob_nop ();
#line 540 "eod.c"
    /* PERFORM LOG-ERROR */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 11;
    frame_ptr->return_address_ptr = &&l_34;
    goto l_11;
    l_34:
    frame_ptr--;

    /* Line: 143       : ADD                : eod.cob */
#line 143 "eod.cob"
    cob_nop ();
#line 554 "eod.c"
    cob_add_int (&f_45, 1, 0);

    /* Line: 144       : EXIT PARAGRAPH     : eod.cob */
#line 144 "eod.cob"
    cob_nop ();
#line 560 "eod.c"
    goto l_10;
  }

  /* Line: 147       : IF                 : eod.cob */
#line 147 "eod.cob"
  cob_nop ();
#line 567 "eod.c"
  if ((((int)(int)(*(b_27 + 5) - (unsigned char)'D') != 0) && 
      ((int)(int)(*(b_27 + 5) - (unsigned char)'W') != 0)))
  {

    /* Line: 148       : MOVE               : eod.cob */
#line 148 "eod.cob"
    cob_nop ();
#line 575 "eod.c"
    cob_move ((cob_field *)&c_2, &f_48);

    /* Line: 149       : PERFORM            : eod.cob */
#line 149 "eod.cob"
    cob_nop ();
#line 581 "eod.c"
    /* PERFORM LOG-ERROR */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 11;
    frame_ptr->return_address_ptr = &&l_35;
    goto l_11;
    l_35:
    frame_ptr--;

    /* Line: 150       : ADD                : eod.cob */
#line 150 "eod.cob"
    cob_nop ();
#line 595 "eod.c"
    cob_add_int (&f_45, 1, 0);

    /* Line: 151       : EXIT PARAGRAPH     : eod.cob */
#line 151 "eod.cob"
    cob_nop ();
#line 601 "eod.c"
    goto l_10;
  }

  /* Line: 154       : IF                 : eod.cob */
#line 154 "eod.cob"
  cob_nop ();
#line 608 "eod.c"
  if (((int)cob_cmp_llint (&f_26, 0LL) == 0))
  {

    /* Line: 155       : MOVE               : eod.cob */
#line 155 "eod.cob"
    cob_nop ();
#line 615 "eod.c"
    cob_move ((cob_field *)&c_3, &f_48);

    /* Line: 156       : PERFORM            : eod.cob */
#line 156 "eod.cob"
    cob_nop ();
#line 621 "eod.c"
    /* PERFORM LOG-ERROR */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 11;
    frame_ptr->return_address_ptr = &&l_36;
    goto l_11;
    l_36:
    frame_ptr--;

    /* Line: 157       : ADD                : eod.cob */
#line 157 "eod.cob"
    cob_nop ();
#line 635 "eod.c"
    cob_add_int (&f_45, 1, 0);

    /* Line: 158       : EXIT PARAGRAPH     : eod.cob */
#line 158 "eod.cob"
    cob_nop ();
#line 641 "eod.c"
    goto l_10;
  }

  /* Line: 161       : IF                 : eod.cob */
#line 161 "eod.cob"
  cob_nop ();
#line 648 "eod.c"
  if (((int)(int)(*(b_27 + 5) - (unsigned char)'D') == 0))
  {

    /* Line: 162       : ADD                : eod.cob */
#line 162 "eod.cob"
    cob_nop ();
#line 655 "eod.c"
    cob_add (&f_20, &f_26, 0);

    /* Line: 163       : ADD                : eod.cob */
#line 163 "eod.cob"
    cob_nop ();
#line 661 "eod.c"
    cob_add (&f_46, &f_26, 0);

    /* Line: 164       : ADD                : eod.cob */
#line 164 "eod.cob"
    cob_nop ();
#line 667 "eod.c"
    cob_add_int (&f_44, 1, 0);

    /* Line: 165       : EXIT PARAGRAPH     : eod.cob */
#line 165 "eod.cob"
    cob_nop ();
#line 673 "eod.c"
    goto l_10;
  }

  /* Line: 168       : IF                 : eod.cob */
#line 168 "eod.cob"
  cob_nop ();
#line 680 "eod.c"
  if (((int)(int)(*(b_27 + 5) - (unsigned char)'W') == 0))
  {

    /* Line: 169       : IF                 : eod.cob */
#line 169 "eod.cob"
    cob_nop ();
#line 687 "eod.c"
    if (((int)memcmp (b_22 + 15, b_27 + 6, 9) < 0))
    {

      /* Line: 170       : MOVE               : eod.cob */
#line 170 "eod.cob"
      cob_nop ();
#line 694 "eod.c"
      cob_move ((cob_field *)&c_4, &f_48);

      /* Line: 171       : PERFORM            : eod.cob */
#line 171 "eod.cob"
      cob_nop ();
#line 700 "eod.c"
      /* PERFORM LOG-ERROR */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 11;
      frame_ptr->return_address_ptr = &&l_37;
      goto l_11;
      l_37:
      frame_ptr--;

      /* Line: 172       : ADD                : eod.cob */
#line 172 "eod.cob"
      cob_nop ();
#line 714 "eod.c"
      cob_add_int (&f_45, 1, 0);
    }
    else
    {
      /* ELSE */

      /* Line: 174       : SUBTRACT           : eod.cob */
#line 174 "eod.cob"
      cob_nop ();
#line 724 "eod.c"
      cob_sub (&f_20, &f_26, 0);

      /* Line: 175       : ADD                : eod.cob */
#line 175 "eod.cob"
      cob_nop ();
#line 730 "eod.c"
      cob_add (&f_47, &f_26, 0);

      /* Line: 176       : ADD                : eod.cob */
#line 176 "eod.cob"
      cob_nop ();
#line 736 "eod.c"
      cob_add_int (&f_44, 1, 0);
    }

    /* Line: 178       : EXIT PARAGRAPH     : eod.cob */
#line 178 "eod.cob"
    cob_nop ();
#line 743 "eod.c"
    goto l_10;
  }

  /* Implicit EXIT label */
  l_10:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 9)
    goto *frame_ptr->return_address_ptr;

  /* Line: 181       : Paragraph LOG-ERROR               : eod.cob */
  l_11:;
#line 181 "eod.cob"
  PARAGRAPH_LOG__ERROR_l_11:	cob_nop ();
#line 758 "eod.c"

  /* Line: 182       : MOVE               : eod.cob */
#line 182 "eod.cob"
  cob_nop ();
#line 763 "eod.c"
  memset (b_37, 32, 120);

  /* Line: 183       : MOVE               : eod.cob */
#line 183 "eod.cob"
  cob_nop ();
#line 769 "eod.c"
  cob_move (&f_26, &f_49);

  /* Line: 184       : STRING             : eod.cob */
#line 184 "eod.cob"
  cob_nop ();
#line 775 "eod.c"
  cob_string_init (&f_36, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_5);
  cob_string_append (&f_24);
  cob_string_append ((cob_field *)&c_6);
  cob_string_append (&f_25);
  cob_string_append ((cob_field *)&c_7);
  cob_string_append (&f_49);
  cob_string_append ((cob_field *)&c_8);
  cob_string_append (&f_48);
  cob_string_finish ();

  /* Line: 192       : WRITE              : eod.cob */
#line 192 "eod.cob"
  cob_nop ();
#line 791 "eod.c"
  cob_write (h_ERROR_FILE, &f_36, 2162689, NULL, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_38;
    goto l_1;
    l_38:
    frame_ptr--;
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 11)
    goto *frame_ptr->return_address_ptr;

  /* Line: 194       : Paragraph WRITE-UPDATED-MASTER    : eod.cob */
  l_12:;
#line 194 "eod.cob"
  PARAGRAPH_WRITE__UPDATED__MASTER_l_12:	cob_nop ();
#line 814 "eod.c"

  /* Line: 195       : MOVE               : eod.cob */
#line 195 "eod.cob"
  cob_nop ();
#line 819 "eod.c"
  memcpy (b_33, b_22, 5);

  /* Line: 196       : MOVE               : eod.cob */
#line 196 "eod.cob"
  cob_nop ();
#line 825 "eod.c"
  memcpy (b_33 + 5, b_22 + 5, 10);

  /* Line: 197       : MOVE               : eod.cob */
#line 197 "eod.cob"
  cob_nop ();
#line 831 "eod.c"
  memcpy (b_33 + 15, b_22 + 15, 9);

  /* Line: 198       : MOVE               : eod.cob */
#line 198 "eod.cob"
  cob_nop ();
#line 837 "eod.c"
  *(b_33 + 24) = *(b_22 + 24);

  /* Line: 199       : WRITE              : eod.cob */
#line 199 "eod.cob"
  cob_nop ();
#line 843 "eod.c"
  cob_write (h_ACCT_NEW, &f_28, 2162689, NULL, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_39;
    goto l_1;
    l_39:
    frame_ptr--;
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 12)
    goto *frame_ptr->return_address_ptr;

  /* Line: 201       : Paragraph WRITE-TRAILING-TRANS-ERRORS: eod.cob */
  l_13:;
#line 201 "eod.cob"
  PARAGRAPH_WRITE__TRAILING__TRANS__ERRORS_l_13:	cob_nop ();
#line 866 "eod.c"

  /* Line: 202       : PERFORM            : eod.cob */
#line 202 "eod.cob"
  cob_nop ();
#line 871 "eod.c"
  for (;;)
  {
    /* Line: 202       : UNTIL              : eod.cob */
#line 202 "eod.cob"
    cob_nop ();
#line 877 "eod.c"
    if (((int)(int)(*(b_40) - (unsigned char)'Y') == 0))
      break;

    /* Line: 203       : MOVE               : eod.cob */
#line 203 "eod.cob"
    cob_nop ();
#line 884 "eod.c"
    cob_move ((cob_field *)&c_9, &f_48);

    /* Line: 204       : PERFORM            : eod.cob */
#line 204 "eod.cob"
    cob_nop ();
#line 890 "eod.c"
    /* PERFORM LOG-ERROR */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 11;
    frame_ptr->return_address_ptr = &&l_40;
    goto l_11;
    l_40:
    frame_ptr--;

    /* Line: 205       : ADD                : eod.cob */
#line 205 "eod.cob"
    cob_nop ();
#line 904 "eod.c"
    cob_add_int (&f_45, 1, 0);

    /* Line: 206       : PERFORM            : eod.cob */
#line 206 "eod.cob"
    cob_nop ();
#line 910 "eod.c"
    /* PERFORM READ-TRANS */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 7;
    frame_ptr->return_address_ptr = &&l_41;
    goto l_7;
    l_41:
    frame_ptr--;
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 13)
    goto *frame_ptr->return_address_ptr;

  /* Line: 209       : Paragraph WRITE-REPORT            : eod.cob */
  l_14:;
#line 209 "eod.cob"
  PARAGRAPH_WRITE__REPORT_l_14:	cob_nop ();
#line 930 "eod.c"

  /* Line: 210       : MOVE               : eod.cob */
#line 210 "eod.cob"
  cob_nop ();
#line 935 "eod.c"
  memset (b_35, 32, 80);

  /* Line: 211       : WRITE              : eod.cob */
#line 211 "eod.cob"
  cob_nop ();
#line 941 "eod.c"
  cob_move ((cob_field *)&c_10, &f_34);
  cob_write (h_REPORT_FILE, &f_34, 2162689, NULL, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_42;
    goto l_1;
    l_42:
    frame_ptr--;
  }

  /* Line: 213       : MOVE               : eod.cob */
#line 213 "eod.cob"
  cob_nop ();
#line 960 "eod.c"
  cob_move (&f_43, &f_49);

  /* Line: 214       : MOVE               : eod.cob */
#line 214 "eod.cob"
  cob_nop ();
#line 966 "eod.c"
  memset (b_35, 32, 80);

  /* Line: 215       : STRING             : eod.cob */
#line 215 "eod.cob"
  cob_nop ();
#line 972 "eod.c"
  cob_string_init (&f_34, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_11);
  cob_string_append (&f_49);
  cob_string_finish ();

  /* Line: 218       : WRITE              : eod.cob */
#line 218 "eod.cob"
  cob_nop ();
#line 982 "eod.c"
  cob_write (h_REPORT_FILE, &f_34, 2162689, NULL, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_43;
    goto l_1;
    l_43:
    frame_ptr--;
  }

  /* Line: 220       : MOVE               : eod.cob */
#line 220 "eod.cob"
  cob_nop ();
#line 1000 "eod.c"
  cob_move (&f_44, &f_49);

  /* Line: 221       : MOVE               : eod.cob */
#line 221 "eod.cob"
  cob_nop ();
#line 1006 "eod.c"
  memset (b_35, 32, 80);

  /* Line: 222       : STRING             : eod.cob */
#line 222 "eod.cob"
  cob_nop ();
#line 1012 "eod.c"
  cob_string_init (&f_34, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_12);
  cob_string_append (&f_49);
  cob_string_finish ();

  /* Line: 225       : WRITE              : eod.cob */
#line 225 "eod.cob"
  cob_nop ();
#line 1022 "eod.c"
  cob_write (h_REPORT_FILE, &f_34, 2162689, NULL, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_44;
    goto l_1;
    l_44:
    frame_ptr--;
  }

  /* Line: 227       : MOVE               : eod.cob */
#line 227 "eod.cob"
  cob_nop ();
#line 1040 "eod.c"
  cob_move (&f_45, &f_49);

  /* Line: 228       : MOVE               : eod.cob */
#line 228 "eod.cob"
  cob_nop ();
#line 1046 "eod.c"
  memset (b_35, 32, 80);

  /* Line: 229       : STRING             : eod.cob */
#line 229 "eod.cob"
  cob_nop ();
#line 1052 "eod.c"
  cob_string_init (&f_34, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_13);
  cob_string_append (&f_49);
  cob_string_finish ();

  /* Line: 232       : WRITE              : eod.cob */
#line 232 "eod.cob"
  cob_nop ();
#line 1062 "eod.c"
  cob_write (h_REPORT_FILE, &f_34, 2162689, NULL, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_45;
    goto l_1;
    l_45:
    frame_ptr--;
  }

  /* Line: 234       : MOVE               : eod.cob */
#line 234 "eod.cob"
  cob_nop ();
#line 1080 "eod.c"
  cob_move (&f_46, &f_49);

  /* Line: 235       : MOVE               : eod.cob */
#line 235 "eod.cob"
  cob_nop ();
#line 1086 "eod.c"
  memset (b_35, 32, 80);

  /* Line: 236       : STRING             : eod.cob */
#line 236 "eod.cob"
  cob_nop ();
#line 1092 "eod.c"
  cob_string_init (&f_34, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_14);
  cob_string_append (&f_49);
  cob_string_finish ();

  /* Line: 239       : WRITE              : eod.cob */
#line 239 "eod.cob"
  cob_nop ();
#line 1102 "eod.c"
  cob_write (h_REPORT_FILE, &f_34, 2162689, NULL, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_46;
    goto l_1;
    l_46:
    frame_ptr--;
  }

  /* Line: 241       : MOVE               : eod.cob */
#line 241 "eod.cob"
  cob_nop ();
#line 1120 "eod.c"
  cob_move (&f_47, &f_49);

  /* Line: 242       : MOVE               : eod.cob */
#line 242 "eod.cob"
  cob_nop ();
#line 1126 "eod.c"
  memset (b_35, 32, 80);

  /* Line: 243       : STRING             : eod.cob */
#line 243 "eod.cob"
  cob_nop ();
#line 1132 "eod.c"
  cob_string_init (&f_34, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_15);
  cob_string_append (&f_49);
  cob_string_finish ();

  /* Line: 246       : WRITE              : eod.cob */
#line 246 "eod.cob"
  cob_nop ();
#line 1142 "eod.c"
  cob_write (h_REPORT_FILE, &f_34, 2162689, NULL, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_47;
    goto l_1;
    l_47:
    frame_ptr--;
  }

  /* Line: 248       : MOVE               : eod.cob */
#line 248 "eod.cob"
  cob_nop ();
#line 1160 "eod.c"
  memset (b_35, 32, 80);

  /* Line: 249       : WRITE              : eod.cob */
#line 249 "eod.cob"
  cob_nop ();
#line 1166 "eod.c"
  cob_move ((cob_field *)&c_16, &f_34);
  cob_write (h_REPORT_FILE, &f_34, 2162689, NULL, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_48;
    goto l_1;
    l_48:
    frame_ptr--;
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 14)
    goto *frame_ptr->return_address_ptr;

  /* Line: 251       : Paragraph CLOSE-FILES             : eod.cob */
  l_15:;
#line 251 "eod.cob"
  PARAGRAPH_CLOSE__FILES_l_15:	cob_nop ();
#line 1190 "eod.c"

  /* Line: 252       : CLOSE              : eod.cob */
#line 252 "eod.cob"
  cob_nop ();
#line 1195 "eod.c"
  cob_close (h_ACCT_MASTER, NULL, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_49;
    goto l_1;
    l_49:
    frame_ptr--;
  }

  /* Line: 253       : CLOSE              : eod.cob */
#line 253 "eod.cob"
  cob_nop ();
#line 1213 "eod.c"
  cob_close (h_TRANS_FILE, NULL, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_50;
    goto l_1;
    l_50:
    frame_ptr--;
  }

  /* Line: 254       : CLOSE              : eod.cob */
#line 254 "eod.cob"
  cob_nop ();
#line 1231 "eod.c"
  cob_close (h_ACCT_NEW, NULL, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_51;
    goto l_1;
    l_51:
    frame_ptr--;
  }

  /* Line: 255       : CLOSE              : eod.cob */
#line 255 "eod.cob"
  cob_nop ();
#line 1249 "eod.c"
  cob_close (h_REPORT_FILE, NULL, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_52;
    goto l_1;
    l_52:
    frame_ptr--;
  }

  /* Line: 256       : CLOSE              : eod.cob */
#line 256 "eod.cob"
  cob_nop ();
#line 1267 "eod.c"
  cob_close (h_ERROR_FILE, NULL, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_53;
    goto l_1;
    l_53:
    frame_ptr--;
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 15)
    goto *frame_ptr->return_address_ptr;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;


  /* Line: 0         : Paragraph Default Error Handler   : eod.cob */
  l_1:;

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS))
  	cob_fatal_error (COB_FERROR_FILE);

  /* Implicit Default Error Handler return */
  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address_ptr;

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);

  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  EOD_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field EOF-MASTER */
#line 66 "eod.cob"
  cob_nop ();
#line 1351 "eod.c"
  *(cob_u8_ptr)(b_38) = (unsigned char)'N';

  /* initialize field EOF-TRANS */
#line 68 "eod.cob"
  cob_nop ();
#line 1357 "eod.c"
  *(cob_u8_ptr)(b_40) = (unsigned char)'N';

  /* initialize field WS-TRANS-READ */
#line 74 "eod.cob"
  cob_nop ();
#line 1363 "eod.c"
  memset (b_42, 48, 7);
  /* initialize field WS-TRANS-OK */
#line 75 "eod.cob"
  cob_nop ();
#line 1368 "eod.c"
  memset (b_42 + 7, 48, 7);
  /* initialize field WS-TRANS-FAIL */
#line 76 "eod.cob"
  cob_nop ();
#line 1373 "eod.c"
  memset (b_42 + 14, 48, 7);
  /* initialize field WS-TOTAL-DEPOSIT */
#line 77 "eod.cob"
  cob_nop ();
#line 1378 "eod.c"
  cob_move ((cob_field *)&c_17, &f_46);
  /* initialize field WS-TOTAL-WITHDRAW */
#line 78 "eod.cob"
  cob_nop ();
#line 1383 "eod.c"
  cob_move ((cob_field *)&c_17, &f_47);

  /* initialize field WS-REASON */
#line 80 "eod.cob"
  cob_nop ();
#line 1389 "eod.c"
  memset (b_48, (unsigned char)' ', 60);

  /* initialize field WS-AMOUNT-DISP */
#line 82 "eod.cob"
  cob_nop ();
#line 1395 "eod.c"
  cob_move (&cob_all_zero, &f_49);

  /* initialize field WS-BALANCE-DISP */
#line 83 "eod.cob"
  cob_nop ();
#line 1401 "eod.c"
  cob_move (&cob_all_zero, COB_SET_FLD (f0, 14, b_50, &a_6));

  /* initialize field WS-AMOUNT-DISP-STR */
#line 84 "eod.cob"
  cob_nop ();
#line 1407 "eod.c"
  memset (b_51, (unsigned char)' ', 15);

  /* initialize field WS-BALANCE-DISP-STR */
#line 85 "eod.cob"
  cob_nop ();
#line 1413 "eod.c"
  memset (b_52, (unsigned char)' ', 15);


  /* File initialization for ACCT-MASTER */
  cob_file_malloc (&h_ACCT_MASTER, NULL, 0, 0);
  h_ACCT_MASTER->select_name = (const char *)"ACCT-MASTER";
  h_ACCT_MASTER->file_status = h_ACCT_MASTER_status;
  memset (h_ACCT_MASTER_status, '0', 2);
  h_ACCT_MASTER->assign = (cob_field *)&c_18;
  h_ACCT_MASTER->record = &f_22;
  h_ACCT_MASTER->variable_record = NULL;
  h_ACCT_MASTER->record_min = 0;
  h_ACCT_MASTER->record_max = 25;
  h_ACCT_MASTER->file = NULL;
  h_ACCT_MASTER->organization = 1;
  h_ACCT_MASTER->access_mode = 1;
  h_ACCT_MASTER->lock_mode = 0;
  h_ACCT_MASTER->open_mode = 0;
  h_ACCT_MASTER->flag_optional = 0;
  h_ACCT_MASTER->flag_line_adv = 0;
  h_ACCT_MASTER->flag_select_features = 0;

  /* File initialization for TRANS-FILE */
  cob_file_malloc (&h_TRANS_FILE, NULL, 0, 0);
  h_TRANS_FILE->select_name = (const char *)"TRANS-FILE";
  h_TRANS_FILE->file_status = h_TRANS_FILE_status;
  memset (h_TRANS_FILE_status, '0', 2);
  h_TRANS_FILE->assign = (cob_field *)&c_19;
  h_TRANS_FILE->record = &f_27;
  h_TRANS_FILE->variable_record = NULL;
  h_TRANS_FILE->record_min = 0;
  h_TRANS_FILE->record_max = 15;
  h_TRANS_FILE->file = NULL;
  h_TRANS_FILE->organization = 1;
  h_TRANS_FILE->access_mode = 1;
  h_TRANS_FILE->lock_mode = 0;
  h_TRANS_FILE->open_mode = 0;
  h_TRANS_FILE->flag_optional = 0;
  h_TRANS_FILE->flag_line_adv = 0;
  h_TRANS_FILE->flag_select_features = 0;

  /* File initialization for ACCT-NEW */
  cob_file_malloc (&h_ACCT_NEW, NULL, 0, 0);
  h_ACCT_NEW->select_name = (const char *)"ACCT-NEW";
  h_ACCT_NEW->file_status = h_ACCT_NEW_status;
  memset (h_ACCT_NEW_status, '0', 2);
  h_ACCT_NEW->assign = (cob_field *)&c_20;
  h_ACCT_NEW->record = &f_33;
  h_ACCT_NEW->variable_record = NULL;
  h_ACCT_NEW->record_min = 0;
  h_ACCT_NEW->record_max = 25;
  h_ACCT_NEW->file = NULL;
  h_ACCT_NEW->organization = 1;
  h_ACCT_NEW->access_mode = 1;
  h_ACCT_NEW->lock_mode = 0;
  h_ACCT_NEW->open_mode = 0;
  h_ACCT_NEW->flag_optional = 0;
  h_ACCT_NEW->flag_line_adv = 0;
  h_ACCT_NEW->flag_select_features = 0;

  /* File initialization for REPORT-FILE */
  cob_file_malloc (&h_REPORT_FILE, NULL, 0, 0);
  h_REPORT_FILE->select_name = (const char *)"REPORT-FILE";
  h_REPORT_FILE->file_status = h_REPORT_FILE_status;
  memset (h_REPORT_FILE_status, '0', 2);
  h_REPORT_FILE->assign = (cob_field *)&c_21;
  h_REPORT_FILE->record = &f_35;
  h_REPORT_FILE->variable_record = NULL;
  h_REPORT_FILE->record_min = 0;
  h_REPORT_FILE->record_max = 80;
  h_REPORT_FILE->file = NULL;
  h_REPORT_FILE->organization = 1;
  h_REPORT_FILE->access_mode = 1;
  h_REPORT_FILE->lock_mode = 0;
  h_REPORT_FILE->open_mode = 0;
  h_REPORT_FILE->flag_optional = 0;
  h_REPORT_FILE->flag_line_adv = 0;
  h_REPORT_FILE->flag_select_features = 0;

  /* File initialization for ERROR-FILE */
  cob_file_malloc (&h_ERROR_FILE, NULL, 0, 0);
  h_ERROR_FILE->select_name = (const char *)"ERROR-FILE";
  h_ERROR_FILE->file_status = h_ERROR_FILE_status;
  memset (h_ERROR_FILE_status, '0', 2);
  h_ERROR_FILE->assign = (cob_field *)&c_22;
  h_ERROR_FILE->record = &f_37;
  h_ERROR_FILE->variable_record = NULL;
  h_ERROR_FILE->record_min = 0;
  h_ERROR_FILE->record_max = 120;
  h_ERROR_FILE->file = NULL;
  h_ERROR_FILE->organization = 1;
  h_ERROR_FILE->access_mode = 1;
  h_ERROR_FILE->lock_mode = 0;
  h_ERROR_FILE->open_mode = 0;
  h_ERROR_FILE->flag_optional = 0;
  h_ERROR_FILE->flag_line_adv = 0;
  h_ERROR_FILE->flag_select_features = 0;

  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'EOD' */

/* Initialize module structure for EOD */
static void EOD_module_init (cob_module *module)
{
  module->module_name = "EOD";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())EOD;
  module->module_cancel.funcptr = (void *(*)())EOD_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

