/* Generated by           cobc 3.2.0 */
/* Generated from         eod.cob */
/* Generated at           Feb 03 2026 21:12:31 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -g eod.cob */

/* Program local variables for 'EOD' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* File ACCT-MASTER */
static cob_file		*h_ACCT_MASTER = NULL;
static unsigned char	h_ACCT_MASTER_status[4];

/* File TRANS-FILE */
static cob_file		*h_TRANS_FILE = NULL;
static unsigned char	h_TRANS_FILE_status[4];

/* File ACCT-NEW */
static cob_file		*h_ACCT_NEW = NULL;
static unsigned char	h_ACCT_NEW_status[4];

/* File REPORT-FILE */
static cob_file		*h_REPORT_FILE = NULL;
static unsigned char	h_REPORT_FILE_status[4];

/* File ERROR-FILE */
static cob_file		*h_ERROR_FILE = NULL;
static unsigned char	h_ERROR_FILE_status[4];

/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Local cob_field items */
cob_field		f0;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_22[25] __attribute__((aligned));	/* ACCT-MASTER Record */
static cob_u8_t	b_27[15] __attribute__((aligned));	/* TRANS-FILE Record */
static cob_u8_t	b_33[25] __attribute__((aligned));	/* ACCT-NEW Record */
static cob_u8_t	b_35[80] __attribute__((aligned));	/* REPORT-FILE Record */
static cob_u8_t	b_37[120] __attribute__((aligned));	/* ERROR-FILE Record */
static cob_u8_t	b_38[1] __attribute__((aligned));	/* EOF-MASTER */
static cob_u8_t	b_40[1] __attribute__((aligned));	/* EOF-TRANS */
static cob_u8_t	b_42[43] __attribute__((aligned));	/* WS-COUNTERS */
static cob_u8_t	b_48[60] __attribute__((aligned));	/* WS-REASON */
static cob_u8_t	b_49[14] __attribute__((aligned));	/* WS-AMOUNT-DISP */
static cob_u8_t	b_50[14] __attribute__((aligned));	/* WS-BALANCE-DISP */
static cob_u8_t	b_51[15] __attribute__((aligned));	/* WS-AMOUNT-DISP-STR */
static cob_u8_t	b_52[15] __attribute__((aligned));	/* WS-BALANCE-DISP-STR */

/* End of local data storage */


/* Fields (local) */
static cob_field f_20	= {9, b_22 + 15, &a_4};	/* AM-BALANCE */
static cob_field f_22	= {25, b_22, &a_3};	/* ACCT-MASTER Record */
static cob_field f_24	= {5, b_27, &a_3};	/* TR-ACCT-ID */
static cob_field f_25	= {1, b_27 + 5, &a_3};	/* TR-TYPE */
static cob_field f_26	= {9, b_27 + 6, &a_4};	/* TR-AMOUNT */
static cob_field f_27	= {15, b_27, &a_3};	/* TRANS-FILE Record */
static cob_field f_28	= {25, b_33, &a_7};	/* ACCT-NEW-REC */
static cob_field f_33	= {25, b_33, &a_3};	/* ACCT-NEW Record */
static cob_field f_34	= {80, b_35, &a_3};	/* REPORT-LINE */
static cob_field f_35	= {80, b_35, &a_3};	/* REPORT-FILE Record */
static cob_field f_36	= {120, b_37, &a_3};	/* ERROR-LINE */
static cob_field f_37	= {120, b_37, &a_3};	/* ERROR-FILE Record */
static cob_field f_43	= {7, b_42, &a_1};	/* WS-TRANS-READ */
static cob_field f_44	= {7, b_42 + 7, &a_1};	/* WS-TRANS-OK */
static cob_field f_45	= {7, b_42 + 14, &a_1};	/* WS-TRANS-FAIL */
static cob_field f_46	= {11, b_42 + 21, &a_5};	/* WS-TOTAL-DEPOSIT */
static cob_field f_47	= {11, b_42 + 32, &a_5};	/* WS-TOTAL-WITHDRAW */
static cob_field f_48	= {60, b_48, &a_3};	/* WS-REASON */
static cob_field f_49	= {14, b_49, &a_6};	/* WS-AMOUNT-DISP */

/* End of fields */

